In [8]:
import csv
import json
with open('data.csv', mode ='r', encoding="utf-8")as file:
    for lines in file:
        print(lines.strip())
student = {
    "name": "Nguyen Van A",
    "age": 20,
    "major": "Computer Science",
    "gpa": 3.5
}
with open('student.json', 'w') as json_file:
    json.dump(student, json_file, indent=4)
with open('student.json', 'r') as json_file:
    print(json.load(json_file))


"name": "An",

"age": 20,

"scores": [8, 9, 7]
{'name': 'Nguyen Van A', 'age': 20, 'major': 'Computer Science', 'gpa': 3.5}


In [1]:
list = [0 ,1, 2, 3, 4, 5 ,6 ,7 , 8 , 9 ,10]
array_chan = list[0::2]
tuple_array = tuple(list)
dict_array = {i: list[i] for i in range(len(list))}
set_array = set(list)
print("dãy số chẵn là " ,list)
print("tuple  là " ,tuple_array)
print("dict  là " ,dict_array)
print("set  là " ,set_array)

dãy số chẵn là  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
tuple  là  (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
dict  là  {0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10}
set  là  {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}


In [23]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
col0 = A[:, 0]
print(col0)
col2 = A[:2]
print(col2)
print("ma trận con từ hàng 1–2 và cột 2–3",A[1:3, 2:4])
print("Chuyển dtype sang float64",A.astype(np.float64))

[1 4 7]
[[1 2 3]
 [4 5 6]]
ma trận con từ hàng 1–2 và cột 2–3 [[6]
 [9]]
Chuyển dtype sang float64 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [24]:
import pandas as pd

scores = pd.Series([7.5, 8.2, 9.0, 6.8, 8.7])
print(scores)

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [23, 30, 22, 35, 28],
    'Major': ['CS', 'Math', 'Physics', 'Chemistry', 'Biology'],
    'Score': scores   
}

df = pd.DataFrame(data)
print(df)

good_students = df[df["Score"] >= 8]
print(good_students)


0    7.5
1    8.2
2    9.0
3    6.8
4    8.7
dtype: float64
      Name  Age      Major  Score
0    Alice   23         CS    7.5
1      Bob   30       Math    8.2
2  Charlie   22    Physics    9.0
3    David   35  Chemistry    6.8
4      Eva   28    Biology    8.7
      Name  Age    Major  Score
1      Bob   30     Math    8.2
2  Charlie   22  Physics    9.0
4      Eva   28  Biology    8.7


In [29]:
import pandas as pd

student = pd.read_csv('student.csv')
print(student)
scores = pd.read_csv('score.csv')
print(scores)
merged_data = pd.merge(student, scores, on='id')
print(merged_data)

df = pd.merge(student, scores, on="id")

df["min"] = df["score"]
df["max"] = df["score"]
df["mean"] = df["score"]
print(df)
df.to_csv("report.csv", index=False)

   id  name
0   1    An
1   2  Binh
2   3  Chau
   id  score
0   1    8.0
1   2    7.5
2   3    9.2
   id  name  score
0   1    An    8.0
1   2  Binh    7.5
2   3  Chau    9.2
   id  name  score  min  max  mean
0   1    An    8.0  8.0  8.0   8.0
1   2  Binh    7.5  7.5  7.5   7.5
2   3  Chau    9.2  9.2  9.2   9.2


In [31]:
import numpy as np

a = np.array([[1], [2], [3], [4]])   
print("a =\n", a)
print("shape a:", a.shape)
b = np.array([[10, 20, 30, 40, 50]])  
print("b =\n", b)
print("shape b:", b.shape)
c = a * b   
print("a * b =\n", c)
sqrt_c = np.sqrt(c)
log_c = np.log(c)

print("sqrt(c) =\n", sqrt_c)
print("log(c) =\n", log_c)
print("Min theo hàng:", np.min(c, axis=1))
print("Max theo hàng:", np.max(c, axis=1))
print("Mean theo hàng:", np.mean(c, axis=1))
print("Std theo hàng:", np.std(c, axis=1))


a =
 [[1]
 [2]
 [3]
 [4]]
shape a: (4, 1)
b =
 [[10 20 30 40 50]]
shape b: (1, 5)
a * b =
 [[ 10  20  30  40  50]
 [ 20  40  60  80 100]
 [ 30  60  90 120 150]
 [ 40  80 120 160 200]]
sqrt(c) =
 [[ 3.16227766  4.47213595  5.47722558  6.32455532  7.07106781]
 [ 4.47213595  6.32455532  7.74596669  8.94427191 10.        ]
 [ 5.47722558  7.74596669  9.48683298 10.95445115 12.24744871]
 [ 6.32455532  8.94427191 10.95445115 12.64911064 14.14213562]]
log(c) =
 [[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]
 [2.99573227 3.68887945 4.09434456 4.38202663 4.60517019]
 [3.40119738 4.09434456 4.49980967 4.78749174 5.01063529]
 [3.68887945 4.38202663 4.78749174 5.07517382 5.29831737]]
Min theo hàng: [10 20 30 40]
Max theo hàng: [ 50 100 150 200]
Mean theo hàng: [ 30.  60.  90. 120.]
Std theo hàng: [14.14213562 28.28427125 42.42640687 56.56854249]


In [35]:
import pandas as pd
import numpy as np

data = {
    "name": ["An", "Bình", "Châu", "Dũng"],
    "age": [20, np.nan, 22, 21],
    "score": [8.5, np.nan, 7.0, 9.0],
    "city": ["Hà Nội", "HCM", np.nan, "Hà Nội"]
}

df = pd.DataFrame(data)
print(df)
print(df.isna())
df["age"] = df["age"].fillna(df["age"].mean())
df["score"] = df["score"].fillna(df["score"].median())
df["city"] = df["city"].fillna("Unknown")
df["city"] = df["city"].astype("category")

def classify_score(x):
    if x >= 8:
        return "Good"
    elif x >= 6:
        return "Average"
    else:
        return "Bad"

df["score_level"] = df["score"].apply(classify_score)
age_mean = df["age"].mean()
age_std = df["age"].std()

df["age_normalized"] = (df["age"] - age_mean) / age_std
print(df)


   name   age  score    city
0    An  20.0    8.5  Hà Nội
1  Bình   NaN    NaN     HCM
2  Châu  22.0    7.0     NaN
3  Dũng  21.0    9.0  Hà Nội
    name    age  score   city
0  False  False  False  False
1  False   True   True  False
2  False  False  False   True
3  False  False  False  False
   name   age  score     city score_level  age_normalized
0    An  20.0    8.5   Hà Nội        Good       -1.224745
1  Bình  21.0    8.5      HCM        Good        0.000000
2  Châu  22.0    7.0  Unknown     Average        1.224745
3  Dũng  21.0    9.0   Hà Nội        Good        0.000000


In [2]:
# Bài 8
import os
import json
import pandas as pd
import re

folder = "logs"
records = []

pattern = re.compile(r"log_(\d{4}-\d{2}-\d{2})\.json")

for filename in os.listdir(folder):
    match = pattern.match(filename)
    if not match:
        continue
    date = pd.to_datetime(match.group(1))
    
    filepath = os.path.join(folder, filename)
    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)
    
    records.append({
        "date": date,
        "user": data.get("user"),
        "action": data.get("action"),
        "duration": data.get("duration", 0)
    })

df = pd.DataFrame(records)
report = df.groupby("date")["duration"].sum().reset_index()

report.to_csv("daily_report.csv", index=False)

print(report)


        date  duration
0 2024-01-01         5
1 2024-01-02         3
