In [2]:
# Bài 1
import numpy as np

arr1 = np.arange(1, 11, dtype=np.int32)
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.int32)
arr3 = np.array([3.3], dtype=np.float32)

print(f"shape1 = {arr1.size}")
print(f"dtype1 = {arr1.dtype}")
print(f"shape2 = {arr2.size}")
print(f"dtype2 = {arr2.dtype}")
print(f"dtype_float = {arr3.dtype}")

shape1 = 10
dtype1 = int32
shape2 = 9
dtype2 = int32
dtype_float = float32


In [ ]:
# Bài 2
import numpy as np

arr1 = np.arange(1, 11)
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 

print(f"first_elem: {arr1[0]}")
print(f"last_elem: {arr1[-1]}")
print(f"middle_elem: {arr1[(len(arr1) - 1)//2]}")

print(f"sliced_arr: {arr2.flatten()[2:5]}")
print(f"row2: {arr2[2, :]}")
print(f"col3: {arr2[:, 2]}")

first_elem: 1
last_elem: 10
middle_elem: 5
sliced_arr: [3 4 5]
row2: [7 8 9]
col3: [3 6 9]


In [10]:
# Bài 3
import numpy as np

arr = np.array([[88, 35, 62], [11, 98, 34], [64, 24, 48]])

print(f"min: {arr.min()}")
print(f"max: {arr.max()}")
print(f"mean: {arr.mean()}")
print(f"sum: {arr.sum()}")
print(f"std: {arr.std()}")

print(f"sum of column: {arr.sum(axis=0)}")
print(f"mean of column: {arr.mean(axis=0)}")

print(f"sum of row: {arr.sum(axis=1)}")
print(f"mean of row: {arr.mean(axis=1)}")

min: 11
max: 98
mean: 51.55555555555556
sum: 464
std: 27.38252123409754
sum of column: [163 157 144]
mean of column: [54.33333333 52.33333333 48.        ]
sum of row: [185 143 136]
mean of row: [61.66666667 47.66666667 45.33333333]


In [12]:
# Bài 4
import numpy as np

arr1 = np.array([[5,6,8], [7,2,4], [1,6,3]])
arr2 = np.array([10,20,30])

print(f"A + B: {arr1 + arr2}")
print(f"A + B: {arr1 - arr2}")

A + B: [[15 26 38]
 [17 22 34]
 [11 26 33]]
A + B: [[ -5 -14 -22]
 [ -3 -18 -26]
 [ -9 -14 -27]]


In [ ]:
# Bài 5
import numpy as np
import time

arr = np.random.randint(1, 21, 10)
squared = np.multiply(arr, arr)
root = np.sqrt(arr)

added = np.add(arr, 5)
multiplied = np.multiply(arr, 3)
root_ufunc = np.sqrt(arr)

arr2d = np.random.randint(1, 100, (1000, 1000))

start_vec = time.time()
vec_result = arr2d * 2 + 3
end_vec = time.time()

start_loop = time.time()
loop_result = np.zeros_like(arr2d)
for i in range(arr2d.shape[0]):
    for j in range(arr2d.shape[1]):
        loop_result[i, j] = arr2d[i, j] * 2 + 3
end_loop = time.time()

print("1D Array:", arr)
print("squared:", squared)
print("squareRoot:", root)
print("add:", added)
print("multiply:", multiplied)
print("sqrtUfunc:", root_ufunc)
print("vectorized time:", end_vec - start_vec)
print("loop time:", end_loop - start_loop)

1D Array: [ 5 11 18  7 10  9 15  2  3 19]
Squared: [ 25 121 324  49 100  81 225   4   9 361]
SquareRoot: [2.23606798 3.31662479 4.24264069 2.64575131 3.16227766 3.
 3.87298335 1.41421356 1.73205081 4.35889894]
Add: [10 16 23 12 15 14 20  7  8 24]
Multiply: [15 33 54 21 30 27 45  6  9 57]
SqrtUfunc: [2.23606798 3.31662479 4.24264069 2.64575131 3.16227766 3.
 3.87298335 1.41421356 1.73205081 4.35889894]
Vectorized Time: 0.0019426345825195312
Loop Time: 0.3163611888885498


In [19]:
# Bài 6
import numpy as np

arr = np.array([[3, 7, 4, 5],[3, 5, 2, 4],[6, 3, 9, 7],[4, 8, 3, 5]])

print(f"sum of column: {arr.sum(axis=0)}")
print(f"moan of column: {arr.mean(axis=0)}")
print(f"std of column: {arr.std(axis=0)}")

print(f"sum of row: {arr.sum(axis=1)}")
print(f"moan of row: {arr.mean(axis=1)}")
print(f"std of row: {arr.std(axis=1)}")

sum of column: [16 23 18 21]
moan of column: [4.   5.75 4.5  5.25]
std of column: [1.22474487 1.92028644 2.6925824  1.08972474]
sum of row: [19 14 25 20]
moan of row: [4.75 3.5  6.25 5.  ]
std of row: [1.47901995 1.11803399 2.16506351 1.87082869]


In [24]:
# Bài 7
import numpy as np
from datetime import datetime

start = datetime.now()
arr1 = np.array([[ 8, 12, 14,  6,  4],[18, 13,  2,  2, 12],[ 6, 18,  5, 10, 10],[ 9,  2,  4, 12, 12],[ 2,  3,  2, 17,  3]])
arr2 = np.array([10, 20, 30, 40, 50])

print(f"total: {arr1 + arr2}")
print(f"diff: {arr1 - arr2}")
print(f"root: {arr1**(1/2)}")
print(f"sum 5: {arr1 + 5}")

end = datetime.now()
print(f"Time to done: {end - start}")

total: [[18 32 44 46 54]
 [28 33 32 42 62]
 [16 38 35 50 60]
 [19 22 34 52 62]
 [12 23 32 57 53]]
diff: [[ -2  -8 -16 -34 -46]
 [  8  -7 -28 -38 -38]
 [ -4  -2 -25 -30 -40]
 [ -1 -18 -26 -28 -38]
 [ -8 -17 -28 -23 -47]]
root: [[2.82842712 3.46410162 3.74165739 2.44948974 2.        ]
 [4.24264069 3.60555128 1.41421356 1.41421356 3.46410162]
 [2.44948974 4.24264069 2.23606798 3.16227766 3.16227766]
 [3.         1.41421356 2.         3.46410162 3.46410162]
 [1.41421356 1.73205081 1.41421356 4.12310563 1.73205081]]
sum 5: [[13 17 19 11  9]
 [23 18  7  7 17]
 [11 23 10 15 15]
 [14  7  9 17 17]
 [ 7  8  7 22  8]]
Time to done: 0:00:00.002004


In [26]:
# Bài 8
import numpy as np


maxtrix = np.array([[6,9,7],[2,1,5],[7,8,3]])

if np.linalg.det(maxtrix) != 0:
    maxtrix_inv = np.linalg.inv(maxtrix)
    print("\nInverse matrix:\n", maxtrix_inv)
else:
    print("Matrix is not invertible.")

eig_values, eig_vectors = np.linalg.eig(maxtrix)

print("\nEigenvalues:", eig_values)
print("\nEigenvectors:\n", eig_vectors)


Inverse matrix:
 [[-0.3627451   0.28431373  0.37254902]
 [ 0.28431373 -0.30392157 -0.15686275]
 [ 0.08823529  0.14705882 -0.11764706]]

Eigenvalues: [15.56193425 -1.69500073 -3.86693352]

Eigenvectors:
 [[-0.73366783 -0.72778239  0.22947148]
 [-0.30862775  0.68155654 -0.7417394 ]
 [-0.60537626 -0.07624612  0.63021068]]
